### ISSUE TITLE
Library is good but..

### ISSUE THREAD

**Issue by luisgcu** [EnviroDIY/SensorModbusMaster#6]
the library is one of the best out there but has no  modbus error check, is there any one that can contribute for that? 
some of the most common errors.
enum ERR_LIST {
  ERR_NOT_MASTER                = -1,
  ERR_POLLING                        = -2,
  ERR_BUFF_OVERFLOW          = -3,
  ERR_BAD_CRC                       = -4,
  ERR_EXCEPTION                   = -5
};

enum {
  NO_REPLY                          = 255,
  EXC_FUNC_CODE               = 1,
  EXC_ADDR_RANGE            = 2,
  EXC_REGS_QUANT            = 3,
  EXC_EXECUTE                    = 4
};
as referece this library can be used to implement errors check:
[https://github.com/pkourany/ModBus_RS485_Slave](url)

**Comment by SRGDamia1** [comment]
There already are error checks in place, for the response length, sender ID, CRC value, and all the standard modbus exception codes.  It's all in the [sendCommand function](https://github.com/EnviroDIY/SensorModbusMaster/blob/ead3c3ea46a302807cb0e45abf37433a34236cff/src/SensorModbusMaster.cpp#L584).  If the response doesn't pass muster for any reason, the sendCommand returns 0, otherwise it returns the number of bytes received.  So, you'll only get data if there are no errors.  There's not a separate function to check for errors and return the error code.  You can, however, watch for errors by turning on the "debugging" mode.  With debugging on, the type of error will be printed to the debugging port.
